# Generated by Django 5.2.1 on 2025-05-22 09:58

import django.core.validators
import themes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('css_url', models.URLField(validators=[themes.models.validate_asset_url])),
                ('js_url', models.URLField(blank=True, null=True, validators=[themes.models.validate_asset_url])),
                ('primary_color', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
                ('secondary_color', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
                ('sidebar_position', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='left', max_length=10)),
                ('scss_variables', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
